package inter;



import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modal.bean.Produto;
import modal.bean.ProdutoTableModel;
import modal.dao.ProdutoDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pit@g
 */
public class Cadastro_de_produto extends javax.swing.JFrame {
    
    ProdutoTableModel tableModel = new ProdutoTableModel();
    /**
     * Creates new form Cadastro_de_produto
     */
    public Cadastro_de_produto() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jtproduto.getModel();
        jtproduto.setRowSorter(new TableRowSorter(modelo));
        readjttable();
        
    }
    
    
  // saida de dados = Libera lista do banco de dados
    public void readjttable () {
    
    DefaultTableModel modelo = (DefaultTableModel) jtproduto.getModel();
    ProdutoDAO pdao = new ProdutoDAO();
    modelo.setNumRows(0);
    pdao.read().stream().forEach((p) -> {
        modelo.addRow(new Object[]{
            
            p.getId(),
            p.getDescricao(),
            p.getQtd(),
            p.getVlr()
                
        }); });
    
    
    }
    
    
    public void readjttableforid(int id) {
   
    DefaultTableModel modelo = (DefaultTableModel) jtproduto.getModel();
    
    modelo.setNumRows(0);
    ProdutoDAO pdao = new ProdutoDAO();
    
    
        for (Produto p : pdao.readForID(id)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getQtd(),
                p.getVlr()
            });

        }

       
    
    }
    
       public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) jtproduto.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();

        for (Produto p : pdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getQtd(),
                p.getVlr()
            });

        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtproduto = new javax.swing.JTable();
        descri_entrada = new java.awt.TextField();
        quantidade_entrada = new java.awt.TextField();
        valor_entrada = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        btn_cadastro = new java.awt.Button();
        btn_excluir = new java.awt.Button();
        btn_altera = new java.awt.Button();
        btn_busca = new javax.swing.JButton();
        espaco_busca = new javax.swing.JTextField();
        chkid = new javax.swing.JRadioButton();
        chkdesc = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario de Cadastrp de produtos  PhillipeSilva");

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Descrição");

        jtproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Descrição", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtproduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtprodutoMouseClicked(evt);
            }
        });
        jtproduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtprodutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtproduto);

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("Quantidade");

        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setText("Valor");

        btn_cadastro.setLabel("Cadastra Produto");
        btn_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastroActionPerformed(evt);
            }
        });

        btn_excluir.setLabel("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_altera.setLabel("Alterar");
        btn_altera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alteraActionPerformed(evt);
            }
        });

        btn_busca.setText("Buscar Produto");
        btn_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaActionPerformed(evt);
            }
        });

        chkid.setText("Pesquisar por Id");

        chkdesc.setText("Pesquisar por Descrição");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(espaco_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_busca))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(btn_altera, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(descri_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantidade_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valor_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkid)
                                    .addComponent(chkdesc))
                                .addGap(193, 193, 193)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantidade_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descri_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(btn_altera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(chkid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkdesc)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_busca)
                            .addComponent(espaco_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastroActionPerformed
        // TODO add your handling code here:
        Produto p = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        p.setDescricao(descri_entrada.getText());
        p.setQtd(Integer.parseInt(quantidade_entrada.getText()));
        p.setVlr(Double.parseDouble(valor_entrada.getText()));
        dao.Inserir(p); 
        
        descri_entrada.setText("");
        quantidade_entrada.setText("");
        valor_entrada.setText("");
        
        readjttable(); // Atualiza a tabela
    }//GEN-LAST:event_btn_cadastroActionPerformed

    private void btn_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaActionPerformed
    

        //   readJTableForDesc(espaco_busca.getText());
        
        if (chkid.isSelected() == true) {
        
        if ("".equals(espaco_busca.getText())) { readjttable(); } else {
        readjttableforid((Integer.parseInt(espaco_busca.getText())));
        }
        
        }
        
        if (chkdesc.isSelected() == true) {
        
        if ("".equals(espaco_busca.getText())) { readjttable(); } else {
        readJTableForDesc(espaco_busca.getText());
        }
        
        }
        
    }//GEN-LAST:event_btn_buscaActionPerformed

    private void jtprodutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtprodutoMouseClicked
        // TODO add your handling code here:
        
        if (jtproduto.getSelectedRow() != 1) {
        
        descri_entrada.setText(jtproduto.getValueAt(jtproduto.getSelectedRow(), 1).toString());
        quantidade_entrada.setText(jtproduto.getValueAt(jtproduto.getSelectedRow(), 2).toString());
        valor_entrada.setText(jtproduto.getValueAt(jtproduto.getSelectedRow(), 3).toString());
        
        }
        
        
        
    }//GEN-LAST:event_jtprodutoMouseClicked

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        // TODO add your handling code here:
                if (jtproduto.getSelectedRow() != -1) {

            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();

            p.setId((int) jtproduto.getValueAt(jtproduto.getSelectedRow(), 0));
            
            dao.excluir(p);

            descri_entrada.setText("");
            quantidade_entrada.setText("");
            valor_entrada.setText("");

            readjttable();

        } else {
            JOptionPane.showMessageDialog(null, "Nome ou id do produto está errado ou não existe.");
        }

        
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_alteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alteraActionPerformed
        // TODO add your handling code here:
        
        if (jtproduto.getSelectedRow() != -1) {

            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();
     
            p.setDescricao(descri_entrada.getText());
            p.setQtd(Integer.parseInt(quantidade_entrada.getText()));
            p.setVlr(Double.parseDouble(valor_entrada.getText()));
            p.setId((int)jtproduto.getValueAt(jtproduto.getSelectedRow(), 0));
            dao.update(p);

            descri_entrada.setText("");
            quantidade_entrada.setText("");
            valor_entrada.setText("");

            readjttable();
            
        }
        
    }//GEN-LAST:event_btn_alteraActionPerformed

    private void jtprodutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtprodutoKeyReleased
        // TODO add your handling code here:
            if (jtproduto.getSelectedRow() != -1) {

            descri_entrada.setText(jtproduto.getValueAt(jtproduto.getSelectedRow(), 1).toString());
            quantidade_entrada.setText(jtproduto.getValueAt(jtproduto.getSelectedRow(), 2).toString());
            valor_entrada.setText(jtproduto.getValueAt(jtproduto.getSelectedRow(), 3).toString());

        }

    }//GEN-LAST:event_jtprodutoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_de_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_de_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_de_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_de_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_de_produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_altera;
    private javax.swing.JButton btn_busca;
    private java.awt.Button btn_cadastro;
    private java.awt.Button btn_excluir;
    private javax.swing.JRadioButton chkdesc;
    private javax.swing.JRadioButton chkid;
    private java.awt.TextField descri_entrada;
    private javax.swing.JTextField espaco_busca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtproduto;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField quantidade_entrada;
    private java.awt.TextField valor_entrada;
    // End of variables declaration//GEN-END:variables
}
