package inter;


import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modal.bean.Produto;
import modal.dao.ProdutoDAO;
import inter.Cadastro_de_produto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pit@g
 */
public class Jpesquisa_usuario extends javax.swing.JFrame {

    
      // saida de dados = Libera lista do banco de dados
    public void readjttable () {
    
    DefaultTableModel modelo = (DefaultTableModel) jtproduto.getModel();
    ProdutoDAO pdao = new ProdutoDAO();
    modelo.setNumRows(0);
    pdao.read().stream().forEach((p) -> {
        modelo.addRow(new Object[]{
            
            p.getId(),
            p.getDescricao(),
            p.getQtd(),
            p.getVlr()
                
        }); });
    
    
    }
    
    
     public void readjttableforid(int id) {
   
    DefaultTableModel modelo = (DefaultTableModel) jtproduto.getModel();
    
    modelo.setNumRows(0);
    ProdutoDAO pdao = new ProdutoDAO();
    
    
        for (Produto p : pdao.readForID(id)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getQtd(),
                p.getVlr()
            });

        }

       
    
    }
    
       public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) jtproduto.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();

        for (Produto p : pdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getQtd(),
                p.getVlr()
            });

        }

    }


    
    
    
    
    /**
     * Creates new form Jpesquisa_usuario
     */
    public Jpesquisa_usuario() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jtproduto.getModel();
        jtproduto.setRowSorter(new TableRowSorter(modelo));
        readjttable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtproduto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        chkid = new javax.swing.JRadioButton();
        chkdesc = new javax.swing.JRadioButton();
        espaco_busca = new javax.swing.JTextField();
        btn_busca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jtproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Descrição", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtproduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtprodutoMouseClicked(evt);
            }
        });
        jtproduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtprodutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtproduto);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        chkid.setText("Pesquisar por Id");

        chkdesc.setText("Pesquisar por Descrição");

        btn_busca.setText("Buscar Produto");
        btn_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(espaco_busca)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkdesc)
                            .addComponent(chkid)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btn_busca)))
                .addGap(25, 61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(chkid)
                .addGap(18, 18, 18)
                .addComponent(chkdesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(espaco_busca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_busca)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaActionPerformed

        //   readJTableForDesc(espaco_busca.getText());

        if (chkid.isSelected() == true) {

            if ("".equals(espaco_busca.getText())) { readjttable(); } else {
                readjttableforid((Integer.parseInt(espaco_busca.getText())));
            }

        }

        if (chkdesc.isSelected() == true) {

            if ("".equals(espaco_busca.getText())) { readjttable(); } else {
                readJTableForDesc(espaco_busca.getText());
            }

        }

    }//GEN-LAST:event_btn_buscaActionPerformed

    private void jtprodutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtprodutoMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jtprodutoMouseClicked

    private void jtprodutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtprodutoKeyReleased
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jtprodutoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jpesquisa_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jpesquisa_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jpesquisa_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jpesquisa_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jpesquisa_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_busca;
    private javax.swing.JRadioButton chkdesc;
    private javax.swing.JRadioButton chkid;
    private javax.swing.JTextField espaco_busca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtproduto;
    // End of variables declaration//GEN-END:variables
}
